
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * 
 */
public class Screen3 extends javax.swing.JFrame {

    /**
     * Creates new form Screen3
     */
    Displaymanager disp;
    
    public Screen3(Displaymanager d) {
        initComponents();
        this.disp=d;
    }
    public JTextField getjTextField1() {
        return jTextField1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        spiceflight = new javax.swing.JLabel();
        via = new javax.swing.JLabel();
        spicetime = new javax.swing.JLabel();
        silktime = new javax.swing.JLabel();
        totaltime = new javax.swing.JLabel();
        silkflight = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FRSystem");
        setLocation(new java.awt.Point(400, 100));
        setMinimumSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Passenger Detail");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Your Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 260, 180, 35);
        jLabel2.getAccessibleContext().setAccessibleName("Enter your name:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(200, 260, 250, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("BOOK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 370, 110, 40);

        spiceflight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        spiceflight.setForeground(new java.awt.Color(255, 255, 255));
        spiceflight.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(spiceflight);
        spiceflight.setBounds(10, 130, 190, 40);

        via.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        via.setForeground(new java.awt.Color(255, 255, 255));
        via.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(via);
        via.setBounds(340, 130, 170, 40);

        spicetime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        spicetime.setForeground(new java.awt.Color(255, 255, 255));
        spicetime.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(spicetime);
        spicetime.setBounds(10, 160, 310, 40);

        silktime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        silktime.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(silktime);
        silktime.setBounds(10, 190, 250, 40);

        totaltime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totaltime.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(totaltime);
        totaltime.setBounds(340, 190, 200, 40);

        silkflight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        silkflight.setForeground(new java.awt.Color(255, 255, 255));
        silkflight.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(silkflight);
        silkflight.setBounds(340, 160, 200, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Your Flight Information:-");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 90, 360, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(80, 370, 100, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(350, 370, 90, 40);

        jLabel3.setBackground(new java.awt.Color(51, 204, 255));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 550, 500);

        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 550, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String name = getjTextField1().getText();
        name = name.trim();
        if(name.isEmpty())
        {
            JOptionPane.showMessageDialog(new JFrame(),"Enter your name before proceeding");
        }
        else
        {
            
            try {
                disp.s3.setVisible(false);
                disp.displayscreen4();
            } catch (IOException ex) {
                Logger.getLogger(Screen3.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        disp.s3.setVisible(false);
        disp.s2.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JLabel silkflight;
    public javax.swing.JLabel silktime;
    public javax.swing.JLabel spiceflight;
    public javax.swing.JLabel spicetime;
    public javax.swing.JLabel totaltime;
    public javax.swing.JLabel via;
    // End of variables declaration//GEN-END:variables
}
