
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * 
 */
public class Screen4 extends javax.swing.JFrame {

    /**
     * Creates new form Screen4
     */
    
    Displaymanager disp;
    public Screen4(Displaymanager d) {
        initComponents();
        this.disp=d;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        source = new javax.swing.JLabel();
        via = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        spiceflight = new javax.swing.JLabel();
        spicetime = new javax.swing.JLabel();
        silkflight = new javax.swing.JLabel();
        silktime = new javax.swing.JLabel();
        seats = new javax.swing.JLabel();
        totaltime = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 120));
        setMinimumSize(new java.awt.Dimension(650, 500));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 340, 80, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Book Another Flight");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(50, 340, 230, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 500, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Your Booking Informatiom:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 50, 420, 50);

        name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(name);
        name.setBounds(10, 100, 310, 50);

        source.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        source.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(source);
        source.setBounds(260, 100, 240, 50);

        via.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        via.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(via);
        via.setBounds(10, 140, 270, 40);

        name1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name1.setForeground(new java.awt.Color(255, 255, 255));
        name1.setText("Destination : Singapore");
        getContentPane().add(name1);
        name1.setBounds(260, 140, 260, 50);

        spiceflight.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        spiceflight.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(spiceflight);
        spiceflight.setBounds(10, 180, 220, 40);

        spicetime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        spicetime.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(spicetime);
        spicetime.setBounds(260, 180, 320, 50);

        silkflight.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        silkflight.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(silkflight);
        silkflight.setBounds(10, 220, 230, 50);

        silktime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        silktime.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(silktime);
        silktime.setBounds(260, 220, 270, 50);

        seats.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        seats.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(seats);
        seats.setBounds(420, 100, 130, 50);

        totaltime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totaltime.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(totaltime);
        totaltime.setBounds(10, 260, 260, 40);

        date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(date);
        date.setBounds(260, 250, 320, 50);

        jLabel1.setBackground(new java.awt.Color(51, 204, 255));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 500);

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 4, 640, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            this.setVisible(false);
            disp.frsManager.initialize();
        }
        catch (IOException ex) {
            Logger.getLogger(Screen4.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel name;
    public javax.swing.JLabel name1;
    public javax.swing.JLabel seats;
    public javax.swing.JLabel silkflight;
    public javax.swing.JLabel silktime;
    public javax.swing.JLabel source;
    public javax.swing.JLabel spiceflight;
    public javax.swing.JLabel spicetime;
    public javax.swing.JLabel totaltime;
    public javax.swing.JLabel via;
    // End of variables declaration//GEN-END:variables
}
